### PR TITLE
build.py code refinement

### PR DESCRIPTION
**Pull request by iblis17**
Hi!
Please check it commit-by-commit.
I'm ok, also, if we only need the subset of these commits.

### CODE REVIEW

**Comment by BruceSherwood** [comment]
My initial quick reaction is that I don't understand much of this, or what the purpose of the changes is. My impression is that the program would get very much larger, without obvious benefits. One very specific question I have is my failure to understand "use relative path". How can you change ../lib/file to lib/file and have anything still work? A very minor point is that there's a reason for the statement "if True: # minify if True"; changing True to False is useful on the rare occasions when testing requires working with non-minified libraries. I suggest that you post your rationales for the various changes, which would help me understand how to evaluate these proposed changes. Thanks.

**Comment by iblis17** [comment]
This PR only change some coding style stuff. I want to make it easier to trace.
e.g. The `main` block can reveal the main concept: build shader first, then package.

About the coding style, if there are some kind of style make everyone happy, I am also happy to change to it.

---

> My impression is that the program would get very much larger, without obvious benefits.

Hmm... there is no instant benefits for style stuff, but i hope/believe it will be good for maintainability.

---

> One very specific question I have is my failure to understand "use relative path. How can you change ../lib/file to lib/file and have anything still work?

Here is a helper function. Both `combine` and `minify` will invoke it to get correct path.:
https://github.com/BruceSherwood/glowscript/pull/55/commits/47112de9b5159376b732f98162ba3aefce24a9e2#diff-2955d5257f635de1df53f55a171ca5c7R93

Note that the var `src_dir` is from `os.path.dirname(__file__)`

---

> A very minor point is that there's a reason for the statement "if True: # minify if True"; changing True to False is useful on the rare occasions when testing requires working with non-minified libraries.

I think the better solution for this requirement is using the command line flag.
I am imaging this:

```shell
$ build.py --no-mini
...
```

I'm willing to make this if you want. Maybe this feature will be another PR.

**Comment by iblis17** [comment]
This patch based on this PR, make the `build.py` accept command line options.
```shell
└─[iblis@imfsa]% ./build.py -h
usage: build.py [-h] [-s] [--no-min]

optional arguments:
  -h, --help    show this help message and exit
  -s, --shader  Build shader file 'lib/glow/shaders.gen.js' only
  --no-min      Build non-minified libraries only
```
Does it make sense to you?

---

```diff
diff --git a/build.py b/build.py
index 57a5de5..3a3578d 100644
--- a/build.py
+++ b/build.py
@@ -15,10 +15,13 @@ TODO
 from __future__ import division
 from __future__ import print_function
 
-import re
+import argparse
 import os
 import subprocess
 
+from collections import namedtuple
+
+
 # TODO: Extract this information from run.js
 version = "2.2dev"
 src_dir = os.path.dirname(__file__)
@@ -83,6 +86,7 @@ def build_shader():
     shader_file.append('}});')
     with open(output_js, 'w') as f:
         f.writelines('\n'.join(shader_file))
+    print("Shader {!r} built successfully.".format(output_js))
 
 
 def abs_path(p):
@@ -112,12 +116,13 @@ def combine(inlibs):
     return "\n".join(gen())
 
 
-def minify(inlibs, inlibs_nomin, outlib):
+def minify(inlibs, inlibs_nomin, outlib, no_min=False):
     '''
     Do unglify for ``inlibs``
 
     :param inlibs: a list of paths which want to be minify
     :param inlibs_nomin: a list of paths which do *not* want to be minify
+    :param no_min: if True, we build no minified libraries only.
 
     Available environment variable:
 
@@ -127,41 +132,68 @@ def minify(inlibs, inlibs_nomin, outlib):
     uglifyjs = abs_path('build-tools/UglifyJS/bin/uglifyjs')
 
     with open(abs_path(outlib), 'w') as outf:
-        uglify = subprocess.Popen(
-            [node_cmd, uglifyjs],
-            stdin=subprocess.PIPE,
-            stdout=outf,
-            )
-        uglify.communicate(combine(inlibs))
-        rc = uglify.wait()
-
-        if rc != 0:
-            print("Something went wrong on {}".format(outlib))
-        else:
-            print("Uglify {} successfully".format(outlib))
+        if not no_min:
+            uglify = subprocess.Popen(
+                [node_cmd, uglifyjs],
+                stdin=subprocess.PIPE,
+                stdout=outf,
+                )
+            uglify.communicate(combine(inlibs))
+            rc = uglify.wait()
+
+            if rc != 0:
+                print("Something went wrong on {}".format(outlib))
+            else:
+                print("Uglify {} successfully".format(outlib))
 
         if inlibs_nomin:
             outf.write(combine(inlibs_nomin))
 
 
-def build_package():
-    minify(glowscript_libraries["run"], [],
-           "package/glow.{}.min.js".format(version))
-    print('Finished glow run-time package')
-
-    minify(glowscript_libraries["compile"], [],
-           "package/compiler.{}.min.js".format(version))
-    print('Finished compiler package')
-
-    minify(glowscript_libraries["RSrun"], [],
-           "package/RSrun.{}.min.js".format(version))
-    print('Finished RapydScript run-time package')
-
-    minify(glowscript_libraries["RScompile"], [],
-           "package/RScompiler.{}.min.js".format(version))
-    print('Finished GlowScript package')
+def build_package(no_min=False):
+    '''
+    :param no_min: if True, we build no minified libraries only.
+    '''
+    Package = namedtuple('Package',
+                         ('inlibs', 'inlibs_nomin', 'outlib', 'comment'))
+
+    pkgs = (
+        Package(inlibs='run',
+                inlibs_nomin=[],
+                outlib='glow.{}.min.js'.format(version),
+                comment='glow run-time package'),
+        Package(inlibs='compile',
+                inlibs_nomin=[],
+                outlib='compiler.{}.min.js'.format(version),
+                comment='compiler package'),
+        Package(inlibs='RSrun',
+                inlibs_nomin=[],
+                outlib='RSrun.{}.min.js'.format(version),
+                comment='RapydScript run-time package'),
+        Package(inlibs='RScompile',
+                inlibs_nomin=[],
+                outlib='RScompiler.{}.min.js'.format(version),
+                comment='GlowScript package'),
+    )
+
+    for pkg in pkgs:
+        minify(glowscript_libraries[pkg.inlibs],
+               pkg.inlibs_nomin, 'package/{}'.format(pkg.outlib),
+               no_min=no_min)
+        print('Finished {}'.format(pkg.comment))
 
 
 if __name__ == '__main__':
-    build_shader()
-    build_package()
+    parser = argparse.ArgumentParser()
+    parser.add_argument('-s', '--shader', action='store_true', default=False,
+                        help="Build shader file 'lib/glow/shaders.gen.js' only")
+    parser.add_argument('--no-min', dest='no_min', action='store_true',
+                        default=False, help="Build non-minified libraries only")
+
+    args = parser.parse_args()
+
+    if args.shader:
+        build_shader()
+    else:  # default: build all
+        build_shader()
+        build_package(no_min=args.no_min)
```

**Comment by BruceSherwood** [comment]
For my own personal reasons of working style I prefer to run build.py from IDLE, not from a command line, and the (simplistic?) form of the existing build.py suits my needs. I propose that instead of modifying it, you provide your own separate version, which you of course would use, as might others eventually (you would be only the fourth person in 5 years to want to build GlowScript, I believe). We could rename the old version build0.py, which I would continue to use, and name the new one build.py. One thing I would recommend is not to change ../lib/file to lib/file, because there is an advantage to using the same form as must be used in run.js. There is even a note in build.py from David Scherer, "# TODO: Extract this information from run.js"

**Comment by iblis17** [comment]
Ok. I will keep the original `build.py` and named the new on as `build_cli.py`.

About the TODO note: I just found this cool project: http://slimit.readthedocs.io/en/latest/.
How about leveraging it to parse `run.js`? I will try it later!

**Comment by BruceSherwood** [comment]
Let's start over. For simplicity, let's forget all your previous pull requests, which I won't merge. Just present the new file, build_cli.py, as one unitary item. I strongly recommend that build_cli.py use the "../lib/file" syntax that is necessarily used in run.js.

**Comment by iblis17** [comment]
@BruceSherwood I squashed the commits and keep the "../lib/file" path. Please check out it!

**Pull request merged**
